# Active Funding Platforms
github: [Mule-ME]
ko_fi: mulualem

# open_collective: refacto  
# tidelift: npm/refacto 
# Additional Support
custom: [
  'https://github.com/sponsors/Mule-ME',
  'https://buymeacoffee.com/mulualem'
]